### ISSUE TITLE
Invalid URL https://api.github.com for API endpoint: url_1.URL is not a constructor

### ISSUE THREAD

**Issue by kpeters-cbsi** [rhysd/validate-github-token#6]
Using this in my Angular 11 app, I get the above error message. I can remove it by taking a copy of your index.ts and stripping out the line `import { URL } from 'url'`.  I haven't been able to reproduce this outside of an Angular context, however, so you can probably treat this as an FYI rather than a bug report. :)

**Comment by kpeters-cbsi** [comment]
After a little more reading, I think it's because Angular is operating in the browser environment, where `URL` is already defined globally.

**Comment by rhysd** [comment]
I'm not familiar with Angular, but the `url` module is only available in node.js.

I found Chrome team developed polyfill to fill this gap: https://github.com/GoogleChromeLabs/native-url

With rollup bundler, `url` module [can be replaced easily with the polyfill](https://github.com/GoogleChromeLabs/native-url#usage-with-rollup). Perhaps Angular also provides the similar way.

**Comment by kpeters-cbsi** [comment]
Thanks, I'll look into that.
